# fly.toml app configuration file generated for george-gopher-site on 2024-12-30T19:47:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'george-gopher-site'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 70
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 7070
  processes = ['app']

  [[services.ports]]
    port = 70

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
